### ISSUE TITLE
Local references should not be prefixed with model name

### ISSUE THREAD

**Issue by harmen-xb** [CrossBreezeNL/crossmodel#123]
When modeling a data model and somewhere a local object is referenced (for example with inheritance, or relationships) the referenced id should be the local id and not the global one (prefixed with the model name.

Example after creating an inheritance:
```
entity:
    id: DataContainerRelationship
    name: "DataContainerRelationship"
    inherits:
      - crossmodel-common.NamedObject
```

What I would rather see (since NamedObject is in the same model):
```
entity:
    id: DataContainerRelationship
    name: "DataContainerRelationship"
    inherits:
      - NamedObject
```
