### ISSUE TITLE
When adding a source attribute for an existing target attribute mapping it ends up with weird file

### ISSUE THREAD

**Issue by harmen-xb** [CrossBreezeNL/crossmodel#91]
When you use the 'Create mapping' tool in the mapping editor diagram on a target attribute which is already listed in the mapping file, but without sources, and drag a new attribute on it the result intiially seems ok, but when closing the diagram the file gets messed up.

Reproduce steps:
- Open the 'CompleteCustomer_Example' mapping in the mapping diagram
- In the mapping the file already contains a target attribute without source:
```
    target:
        entity: CompleteCustomer
        mappings:
          ...
          - attribute: Today
            customProperties:
              - name: Author
                value: "CrossBreeze"
              - name: ExampleEntityTargetAttribute
```
- In the mapping diagram using the create mapping tool when you now drag a source attribute on top of the Today target attribute the diagram gets an error state because the target attribute now has two mappings.
```
    target:
        entity: CompleteCustomer
        mappings:
          ...
          - attribute: Today
            customProperties:
              - name: Author
                value: "CrossBreeze"
              - name: ExampleEntityTargetAttribute
          - attribute: Today
            sources:
              - Customer.BirthDate
```

Expected behaviour
- The source should have been added to the existing target attribute mapping.
